# Site settings
title: Casper Beyer
email: caspervonb@qup.io
description: >

baseurl: ""
url: "https://caspervonb.github.io"

twitter: caspervonb
github:  caspervonb

amazon: caspbeye-20
analytics: UA-48351156-1
permalink: /:categories/:title/

# Build settings
markdown: redcarpet
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
