# Site settings
title: Casper Beyer
description: Developer, Dork and Designer

baseurl: ""
url: "https://caspervonb.github.io"

email: caspervonb@qup.io
gravatar: 69e75f6897227e93b27154f491b18b43
twitter: caspervonb
github:  caspervonb

amazon: caspbeye-20
analytics: UA-48351156-1
disqus: caspervonb

permalink: /:categories/:title/

# Build settings
paginate: 5
paginate_path: "/page:num"

markdown: redcarpet
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
