# Site settings
title: Casper Beyer
description: This is not a blog

baseurl: ""
url: "https://caspervonb.github.io"

email: caspervonb@qup.io
gravatar: 69e75f6897227e93b27154f491b18b43
twitter: caspervonb
github:  caspervonb

amazon: caspbeye-20
analytics: UA-48351156-1
disqus: caspervonb

permalink: /:categories/:title/

post_thumbnail: https://cloud.githubusercontent.com/assets/157787/6486649/54d38c26-c2c7-11e4-859e-aa463e68b506.png

# Build settings
paginate: 5
paginate_path: "/page:num"

lsi: true
markdown: redcarpet
redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink', 'with_toc_data']

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
